name: Deploy to Test Repo

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Dev Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0   # full repo

      - name: Clean unnecessary files
        run: |
          rm -rf node_modules
          rm -rf .git

      - name: Initialize fresh repo
        run: |
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "Fresh deploy"

      - name: Push to Test_ADAP
        run: |
          git branch -M main
          git push https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/Sherikk786/Test_ADAP.git main --force